#!/bin/sh

EXTENSIONS="js html css py cpp h mm m vsh fsh"

FIND_PATH=$1

if [ -z $1 ]; then
    FIND_PATH="."
fi

for ext in $EXTENSIONS
do
	find $FIND_PATH -type f -iname *.$ext -print0 | xargs -0 sed -i "" -E "s/[[:space:]]*$//"
done